[project]
name = "gemma3serving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hf",
    "torch",
    "torchvision",
    "torchaudio",
    "numpy",
    "vllm==0.15.1",
    "llmcompressor>=0.9.0.1",
    "oneshot>=0.2.0",
    "lm-eval>=0.4.11",
    "transformers==4.57.1",
    "flash-attn>=2.8.3",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }
